### ISSUE TITLE
Zenoh Rust uLink Library: Initial Commit

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-client-zenoh-rust#1]
Implement uTransport & RpcClient interfaces

**Comment by stevenhartley** [comment]
Initial commit of the library, work being done on https://github.com/ZettaScaleLabs/uprotocol-java-ulink-zenoh/tree/initial_version

**Comment by evshary** [comment]
Here is the initial implementation for publisher/subscriber & RpcServer/RpcClient
https://github.com/ZettaScaleLabs/uprotocol-rust-ulink-zenoh/pull/2
I'll send PR after updating the examples by using micro-form Uuri.
It would help a lot if there is any example of how to create micro-form Uuri in uProtocol.

**Comment by stevenhartley** [comment]
@evshary ,
I've added an example in the test for Java, Below that generates an Update notification event emitted from uSubscription service:
```
        UUri uri = UUri.newBuilder()
            .setAuthority(UAuthority.newBuilder()
                .setIp(ByteString.copyFrom(InetAddress.getByName("10.0.3.3").getAddress()))
                .build())
            /* Entity information will be pulled from the generated stubs, for now we hardcode it */
            .setEntity(UEntity.newBuilder()
                .setName("core.usubscription")
                .setId(0)
                .setVersionMajor(3)
                .build())
            /* Resource information is pulled from protobuf generated messages */
            .setResource(UResource.newBuilder()
                .setName(Update.getDescriptor().getName())
                .setInstance(Update.Resources.subscriptions.name())
                .setId(Update.Resources.subscriptions.getNumber())
                .build())
            .build()

```
You can get more info (for Java) here: https://github.com/eclipse-uprotocol/uprotocol-java/blob/main/src/main/java/org/eclipse/uprotocol/uri/README.adoc. Please reach out to Daniel (rust) for examples

**Comment by evshary** [comment]
@stevenhartley I have some follow-up questions:

1. According to the example [here](https://github.com/eclipse-uprotocol/uprotocol-java/blob/main/src/main/java/org/eclipse/uprotocol/uri/README.adoc#21-building-an-rpc-method), does that mean users should generate the ID (number) by themselves based on the rules [here](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#42-micro-uris)?
2. Although Zenoh only uses micro URI, users still need to set the name for entity and resource in their application, right? Is it possible for users to set the ID (number) only?

Thanks for your answer.

**Comment by stevenhartley** [comment]
> @stevenhartley I have some follow-up questions:
> 
> 1. According to the example [here](https://github.com/eclipse-uprotocol/uprotocol-java/blob/main/src/main/java/org/eclipse/uprotocol/uri/README.adoc#21-building-an-rpc-method), does that mean users should generate the ID (number) by themselves based on the rules [here](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#42-micro-uris)?
> 2. Although Zenoh only uses micro URI, users still need to set the name for entity and resource in their application, right? Is it possible for users to set the ID (number) only?
> 
> Thanks for your answer.

Hi @evshary , 
1. By ID do you mean UUID or the UAutority id? Given that UAuthority id, ip, and name are deployment/system specific, the user needs to set this (or can fetch from the "system"
2. We want users to generate resolved URIs meaning it contains names and numbers and are building helper functions/methods for this (in the uService code generators so that the developer will have typed topics.

**Comment by evshary** [comment]
> 1. By ID do you mean UUID or the UAutority id? Given that UAuthority id, ip, and name are deployment/system specific, the user needs to set this (or can fetch from the "system"

I mean UEntity and UResource. Given an example, how do we pick `10203` here? Using random number?

```java
UUri uri = UUri.newBuilder()
    .setAuthority(UAuthority.newBuilder()
        .setName("MyDevice")
        .setIp(ByteString.copyFrom(InetAddress.getByName("192.168.1.100").getAddress()))
        .setId(ByteString.copyFrom("3GTU2NEC8HG403825").build()))
    .setEntity(UEntity.newBuilder()
        .setName("HartleyService")
        .setId(10203)
        .setVersionMajor(1)
        .build())
    .setResource(UResourceBuilder.forRpcRequest("Raise", 10))
    .build();
```

**Comment by stevenhartley** [comment]
they are defined in the service contracts (the service protos). If you want to see how I pull it out, checkout https://github.com/eclipse-uprotocol/uprotocol-java/pull/70/files#diff-9b5b70ab7ae724b6babe8faa5e5fb696d33889f9e9b549eb763ddb311c059ec1 and UriBuilderTest.java that uses the UEntityBuilder.fromProto() and UResourceBuilder.fromProto(). We are re-evaluating how to define the UResource names & ids to make it simpler for developers so no need to pull this java code into any of the other language libraries yet.

**Comment by evshary** [comment]
I see. It makes sense if there is a simple way for developers to get the ID from proto easily. For the time being, I'll use random numbers as ID in Rust examples. I will change it after the API is stable.

**Comment by stevenhartley** [comment]
merged
