### ISSUE TITLE
Move the examples to another repository

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-client-zenoh-rust#11]
We need to move the examples to another repository, just as [up-zenoh-example-cpp](https://github.com/eclipse-uprotocol/up-zenoh-example-cpp) does.
@stevenhartley Could you please create a repository `up-zenoh-example-rust`? To be honest, I'm not sure if you prefer to have different repositories for each language-binding examples or not. Let me know where you want to put the Zenoh Rust examples.

**Comment by stevenhartley** [comment]
Please see https://github.com/eclipse-uprotocol/.eclipsefdn/pull/43, should be merged later today

**Comment by evshary** [comment]
Here is the PR, and I'll remove the examples in up-client-zenoh-rust later.
https://github.com/eclipse-uprotocol/up-zenoh-example-rust/pull/1

**Comment by evshary** [comment]
Done in https://github.com/eclipse-uprotocol/up-zenoh-example-rust/pull/1
