### ISSUE TITLE
Update to use `UListener` interface change within `UTransport`

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-client-zenoh-rust#22]
Hey @evshary -- I think you were saying you had a feature branch updating to use `UListener`.

Could you open a PR supporting those changes now that they have merged?
* https://github.com/eclipse-uprotocol/up-rust/pull/69
* https://github.com/eclipse-uprotocol/up-rust/pull/79
* https://github.com/eclipse-uprotocol/up-rust/pull/81

**Comment by evshary** [comment]
I've heard from @AnotherDaniel that he needs this. I'll work on this.

**Comment by evshary** [comment]
Close with #24
