### ISSUE TITLE
Use different/latest up-rust version

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-client-zenoh-rust#26]
With the recent changes to accommodate current up-rust  status, would it be possible to now change the up-rust dependency in Cargo.toml to just use 'latest' (i.e., remove the rev-pin)?

Reason for the ask is that the current rev forces use of an older up-rust version, which does not contain the recent improvements we did there...

**Comment by AnotherDaniel** [comment]
Ok - but can we then at least raise the dependency to the current head revision? (8048bc0d5b6ca822ce5101ca8fa95d41ea9f7817)

(I can do a PR  -  just want to check with you first...)

**Comment by evshary** [comment]
@AnotherDaniel  I created a PR #27 
It seems like there is no big affection for up-client-zenoh-rust.
I'll merge it if you approve it.

BTW, feel free to let me know anytime if you want to use the feature in the latest up-rust, or it's also ok if you want to create the PR by yourself.

**Comment by AnotherDaniel** [comment]
Hehe, I do have quite some affection for it - you were the first to use up-rust, so special place in my heart :)

Also some time in the next weeks, I will PR a USubscription implementation into here - but still in the middle of all of that.
